<?php
/*---------------------------------------------------------------------
 * @project:	My Flicker Gallery
 * 
 * @Project		My Flicker Gallery Application
 * 
 * --------------------------------------------------------------------
 * Created by ashon on Aug 17, 2012
 * 
 * (c) 2010 - 2012 Copyright Ashon Associates Inc. Web Solutions 
 * 
 * This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * --------------------------------------------------------------------
 */
$layout			= Controller_Layout::getInstance();
$layout->addCSS('css/about.css');
 ?>
<div id="about">
	<h2>So you wanna know About <u><?php echo APP_NAME?></u>!</h2>
	<p>Welcome, my name is <strong>Yinka Kunle, <u>Asonibare</u></strong>. You may call me Yinka because that's what my wife calls me the most;
	or better still, John, if that's too harsh for your tongue. I love writting programmes on computers and ... I can sacrifice my food for the code.
	And guess what, I'm one of those childish dudes who don't like building websites with flashy tools such as macromedia XXX, I love my notepad (eclipse),
	just simply because they are too flashy.</p>
	<p>So about this app., I created it in response to a requirement to showcase my knowledge of PHP and APIs using Yahoo Flickr API. It's simple, it searchs for images from Flickr&trade; server and spits them to the screen.</p>
	<p>I suck a bit at UI so don't ... don't say a thing</p>
	<p>See some of my other works at <a href="http://ashon-associates.com/demos" title="My demos - Yinka Asoniare" target="_blank">http://ashon-associates.com/demos</a></p>
</div>