<?php
/*---------------------------------------------------------------------
 * @project:	My Flicker Gallery
 * 
 * @Project		My Flicker Gallery Application
 * 
 * --------------------------------------------------------------------
 * Created by ashon on Aug 18, 2012
 * 
 * (c) 2010 - 2012 Copyright Ashon Associates Inc. Web Solutions 
 * 
 * This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * --------------------------------------------------------------------
 */
$this->addCSS('css/myflickr.css');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en_US" xml:lang="en_US">
<head profile="http://www.w3.org/2005/10/profile">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="Content-Language" content="en" />
		<title><?php echo $this->getPageTitle() . ' - ' . APP_NAME; ?></title>
		<?php echo $this->getCSS(); ?>
</head>
<body>
	<div id="header">
		<table>
		<tr>
			<td width="70%"><!-- Menu Pane -->
				<h1><?php echo $this->getPageTitle(); ?></h1>
			</td>
			<td>
				<h2><?php echo APP_NAME;?></h2>
			</td>
		</tr>
		<tr>
			<td>
			<div id="menu">
				<ul>
					<li><?php echo $this->fullUrl('Home', null, array('title' => 'home','class' => 'nav-link'));?></li>
					<li><?php echo $this->fullUrl('Search', array('controller' => 'photos', 'action' => 'search'), array('class' => 'nav-link')); ?></a></li>
					<li><?php echo $this->fullUrl('About App', array('controller' => 'home', 'action' => 'about'), array('class' => 'nav-link')); ?></a></li>
				</ul>
			</div>
			</td><!-- End of Menu Pane -->
			<td><!-- Search pane -->
			<div id="search-form">
				<form action="<?php echo $this->fullUrlLink(array('controller' => 'photos', 'action' => 'search'))?>" method="post">
					<label for="search">Search: </label><input type="text" name="q" /><input type="submit" value= "Search" />
					<input type="hidden" name="ashon" value="33" />
				</form>
			</div>
			</td><!-- End of Search pane -->
		</tr></table>
	</div>
	<div id="content">
<?php echo $this->content; ?>
	</div>
	<div id="footer">
		<footer>
		&copy; <?php echo (date('Y') > 2012 ? '2012 - '. date('Y') : '2012'); ?>
		Ashon Associates Inc.
		<p>All code written <a href="http://ashon-associates.com/" title="Check out more about me" target="_blank">by Yinka Asonibare</a> from scratch<small><em> in 2days</em></small></p>
			<p>Flickr is a registered trademark of Yahoo!&trade;</p>
		</footer>
	</div>
	</body>
</html>